-- +goose Up
-- +goose StatementBegin
CREATE TABLE users (
    id bigint primary key generated by default as identity,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null unique,
    password_hash varchar(255),
    created_at timestamp(0) not null default (now() at time zone 'utc'),
    updated_at timestamp(0) not null default (now() at time zone 'utc')
  );
-- +goose StatementEnd

CREATE TABLE sessions (
   id bigint primary key generated by default as identity,
   user_id bigint not null references users(id),
   expires_at timestamp(0),
   created_at timestamp(0) not null default (now() at time zone 'utc'),
   updated_at timestamp(0) not null default (now() at time zone 'utc')
);

-- +goose Down
-- +goose StatementBegin
DROP table users CASCADE;
DROP table sessions;
-- +goose StatementEnd
